### ISSUE TITLE
I can't include mkl.h.

### ISSUE THREAD

**Issue by yongjong111** [chasingegg/Winconv#2]
I'm very interested in this.
I'm going to compile this code but i can't compile.
I can't include mkl.h
what do i have to do?
thanks in advance.

**Comment by chasingegg** [comment]
@yongjong111 Sorry It's been late to reply. Please make sure you have installed Intel MKL correctly. May the install guide [https://software.intel.com/en-us/articles/intel-math-kernel-library-intel-mkl-2018-install-guide](https://software.intel.com/en-us/articles/intel-math-kernel-library-intel-mkl-2018-install-guide) would help you.
